image:
  file: .gitpod.Dockerfile

# This will expose all necessary ports needed for your VNC image
ports:
  - port: 8000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 6379
    onOpen: open-preview
  - port: 5432
    onOpen: open-preview


tasks:
  - init: psql_start
  # - init:  postgres createdb kda && postgres psql && alter user debug with encrypted password 'debug' &&  grant all privileges on database kda to debug && exit
    command: psql_start

  - init: pip3 install -r requirements.txt  && python3 manage.py makemigrations && && python manage.py migrate && python3 manage.py collectstatic 
    command: python3 manage.py runserver 0.0.0.0:8080

  - init: redis-server
    command: redis-server
# tasks:
# - init: >
#     python3 -m pip install -r requirements.txt &&
#     python3 manage.py migrate
#   command: >
#     echo "from locallibrary.settings import *" > locallibrary/local_settings.py &&
#     echo "ALLOWED_HOSTS = ['*']" >> locallibrary/local_settings.py &&
#     export DJANGO_SETTINGS_MODULE=locallibrary.local_settings &&
#     python3 manage.py runserver 0.0.0.0:8080

# tasks: 
#   - command: >
  # postgres createdb kda &&
  # postgres psql &&
  # alter user debug with encrypted password 'debug';
  # grant all privileges on database kda to debug;
  # exit

#   - init: redis-server

#   - init: pip3 install -r requirements.txt
#     command: python3 manage.py makemigrations
#     command: python3 manage.py migrate
#     command: python3 manage.py collectstatic
#     command: python3 manage.py runserver

# vscode:
#   extensions:
#     - jpoissonnier.vscode-styled-components@0.0.28:Qde/ISuGvFTPjoaMf1FmnQ==
#     - paulmolluzzo.convert-css-in-js@1.1.3:YnjK47pXScU3DMFfQzkkOw==
#     - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==

# github:
#   prebuilds:
#     # enable for the master/default branch (defaults to true)
#     master: true
#     # enable for all branches in this repo (defaults to false)
#     branches: true
#     # enable for pull requests coming from this repo (defaults to true)
#     pullRequests: true
#     # enable for pull requests coming from forks (defaults to false)
#     pullRequestsFromForks: true
#     # add a check to pull requests (defaults to true)
#     addCheck: true
#     # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
#     addComment: false
#     # add a "Review in Gitpod" button to the pull request's description (defaults to false)
#     addBadge: false
#     # add a label once the prebuild is ready to pull requests (defaults to false)
#     addLabel: false
